import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { QueryProvider } from "./QueryProvider";
import "./styles/globals.css";

const pretendardStd = localFont({
  src: "./assets/fonts/PretendardStdVariable.woff2",
  display: "swap",
  variable: "--font-pretendard-std",
});

const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--font-inter" });

export const metadata: Metadata = {
  title: "GlobalNomad",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head />
      <body className={`${pretendardStd.variable} ${inter.variable}`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
